// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import { ScrimController } from "@katalyst-interactive/turbo-modal";
import { ModalController } from "@katalyst-interactive/turbo-modal";

application.register("test", ScrimController)
application.register("modal", ModalController)
